name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Lint Code
      run: npm run lint

    - name: Check Formatting
      run: npm run format:staged

    - name: Build the Next.js application
      run: npm run build

    - name: Start the Next.js application
      run: npm run start &

    - name: Run Cypress tests
      run: npm run cypress:run
